- name: ensure console packages installed
  apt: pkg={{ item }} state=latest install_recommends=no
  with_items:
    - cmatrix
    # - cowsay
    - git
    - mc
    # - mp3blaster
    - mmv
    - ncdu
    - qalc
    - ranger
    - sshfs
    - tig
    - tmux
    - unrar
    # - weechat
  become: yes
  tags:
    - console

- name: ensure updated console packages installed
  apt: pkg={{ item }} state=latest install_recommends=no
  when: ansible_distribution_release == "bionic"
  with_items:
    - neofetch
  become: yes
  tags:
    - console
