- name: ensure console packages installed
  apt: pkg={{ item }} state=latest install_recommends=no
  with_items:
    - cmatrix
    # - cowsay
    - git
    - mc
    # - mp3blaster
    - ncdu
    - ranger
    - tig
    - tmux
    - xclip
    - unrar
    # - weechat
  become: yes
  tags:
    - console
