- name: ensure console packages installed
  apt: pkg={{ item }} state=latest install_recommends=no
  with_items:
    - cmatrix
    # - cowsay
    - git
    - mc
    # - mp3blaster
    - mmv
    - mosh
    - ncdu
    - qalc
    - ranger
    - sshfs
    - tig
    - tmux
    - tmuxinator
    - unrar
    # - weechat
  become: yes
  tags:
    - console

- name: ensure latest tmuxinator
  gem:
    name: tmuxinator
    state: latest
  become: yes
  tags:
    - console

- name: ensure youtube ripping
  pip:
    name:
      - mps-youtube
      - pyperclip
      - youtube-dl
  become: yes
  tags:
    - console

- name: ensure updated console packages installed
  apt: pkg={{ item }} state=latest install_recommends=no
  when: ansible_distribution_release == "bionic"
  with_items:
    - neofetch
  become: yes
  tags:
    - console
