- name: ensure partners repo available
  apt_repository: repo='deb http://archive.canonical.com/ubuntu precise partner' state=present
  sudo: yes

- name: ensure desktop packages
  apt: pkg={{ item }} update_cache=yes state=latest install_recommends=no
  with_items:
    - chromium-browser
    - chromium-codecs-ffmpeg
    - ffmpeg
    - firefox
    - flashplugin-installer
    - fonts-ubuntu-font-family-console
    - freerdp-x11
    - lame
    - libavcodec-extra-53
    - libdvdread4
    - mplayer
    - remmina
    - remmina-plugin-rdp
    - remmina-plugin-vnc
    - skype
    - ttf-ubuntu-font-family
    - transmission-gtk
    - ubuntu-restricted-extras
    - unrar
    - vlc
    - youtube-dl
    # manually accept eula
    # - ttf-mscorefonts-installer
    # install the Vista fonts
    # http://plasmasturm.org/code/vistafonts-installer/vistafonts-installer
  sudo: yes
