- name: ensure partners repo available
  apt_repository: repo="deb http://archive.canonical.com/ubuntu {{ ansible_distribution_release }} partner" state=present
  when: ansible_distribution == 'Ubuntu'
  sudo: yes
  tags:
    - desktop

- name: ensure nice icons repo.
  apt_repository: repo='ppa:oranchelo/oranchelo-icon-theme'
  when: ansible_distribution_release == 'bionic'
  sudo: yes
  tags:
    - desktop

- name: ensure desktop packages
  apt: pkg={{ item }} update_cache=yes state=latest install_recommends=no
  with_items:
    - chromium-browser
    - chromium-codecs-ffmpeg
    - ffmpeg
    - firefox
    - gnome-tweak-tool
    - gthumb
    - libdvdread4
    - meld
    - mplayer
    - transmission-gtk
    - vlc
    - xclip
    - youtube-dl
    # manually accept eula
    # - ttf-mscorefonts-installer
  when: ansible_distribution == 'Ubuntu'
  become: yes
  tags:
    - desktop

- name: ensure bloatware-less desktop packages
  apt: pkg={{ item }} state=absent install_recommends=no
  with_items:
    - libreoffice-avmedia-backend-gstreamer
    - libreoffice-calc
    - libreoffice-draw
    - libreoffice-impress
    - libreoffice-math
  when: ansible_distribution == 'Ubuntu'
  become: yes
  tags:
    - desktop

- name: ensure nice icons package
  apt: pkg=oranchelo-icon-theme update_cache=yes state=latest install_recommends=no
  when: ansible_distribution_release == 'bionic'
  become: yes
  tags:
    - desktop

- name: ensure legacy desktop packages
  apt: pkg={{ item }} update_cache=yes state=latest install_recommends=no
  with_items:
    - fonts-ubuntu-font-family-console
    - freerdp-x11
    - lame
    - libavcodec-extra-53
    - remmina
    - remmina-plugin-rdp
    - remmina-plugin-vnc
    - ttf-ubuntu-font-family
    - ubuntu-restricted-extras
    # install the Vista fonts
    # http://plasmasturm.org/code/vistafonts-installer/vistafonts-installer
  when: ansible_distribution_release != 'bionic'
  become: yes
