- name: ensure partners repo available
  apt_repository: repo="deb http://archive.canonical.com/ubuntu {{ ansible_distribution_release }} partner" state=present
  when: ansible_distribution == 'Ubuntu'
  become: yes

- name: ensure desktop packages
  apt: pkg={{ item }} update_cache=yes state=latest install_recommends=no
  with_items:
    - chromium-browser
    - chromium-codecs-ffmpeg
    - ffmpeg
    - firefox
    - libdvdread4
    - meld
    - mplayer
    - transmission-gtk
    - vlc
    - xclip
    - youtube-dl
    # manually accept eula
    # - ttf-mscorefonts-installer
  when: ansible_distribution == 'Ubuntu'
  become: yes

- name: ensure legacy desktop packages
  apt: pkg={{ item }} update_cache=yes state=latest install_recommends=no
  with_items:
    - fonts-ubuntu-font-family-console
    - freerdp-x11
    - lame
    - libavcodec-extra-53
    - remmina
    - remmina-plugin-rdp
    - remmina-plugin-vnc
    - ttf-ubuntu-font-family
    - ubuntu-restricted-extras
    # install the Vista fonts
    # http://plasmasturm.org/code/vistafonts-installer/vistafonts-installer
  when: ansible_distribution_release != 'bionic'
  become: yes
