# run only this task using tags!
#
#   $ ansible-playbook -vv -K --sudo developer.yml --tag eos

- name: ensure updates repo available
  apt_repository: repo='ppa:bmeznarsic/icon-themes'
  when: ansible_distribution_release == "freya"
  sudo: yes
  tags:
    - eos

- name: ensure tweaks packages
  apt: pkg={{ item }} update_cache=yes state=latest
  with_items:
    - elementary-thirdparty-icons
    - elementary-elfaenza-icons
  when: ansible_distribution_release == "freya"
  sudo: yes
  tags:
    - eos

- name: ensure ieos7-icons repo available
  apt_repository: repo='ppa:noobslab/icons'
  sudo: yes
  tags:
    - eos
- name: ensure ieos7-icons available
  apt: pkg=ieos7-icons state=latest
  sudo: yes
  tags:
    - eos

- name: ensure updates repo available
  apt_repository: repo='ppa:versable/elementary-update'
  when: ansible_distribution_release == 'luna'
  sudo: yes
  tags:
    - eos

- name: ensure icons repo available
  apt_repository: repo='ppa:elementary-br/projects'
  when: ansible_distribution_release == 'luna'
  sudo: yes
  tags:
    - eos

- name: ensure tweaks packages
  apt: pkg={{ item }} update_cache=yes state=latest
  with_items:
    - audience
    - elementary-thirdparty-icons
    - elementary-elfaenza-icons
    - elementary-tweaks
    - foto
    - gstreamer0.10-fluendo-mp3
    - ieos7-icons
    - indicator-synapse
    - wingpanel-slim
  when: ansible_distribution_release == 'luna'
  sudo: yes
  tags:
    - eos

- name: ensure ieos7-icons for places/folders; as elFaenza uses eOS stock icons
  command: rm -rf /usr/share/icons/elFaenza/places
  when: ansible_distribution_release == 'luna'
  sudo: yes
  tags:
    - eos
- name: ensure ieos7-icons for places/folders; as elFaenza uses eOS stock icons
  command: ln -s /usr/share/icons/Ieos7/places /usr/share/icons/elFaenza/places
  when: ansible_distribution_release == 'luna'
  sudo: yes
  tags:
    - eos

# finish theme installation in the Appearance settings:
#   * Window Decoration Theme: MoonLion
#   * Interface Theme: MoonLion
#   * Icon Theme: elFaenza

- name: clone MoonLion theme
  git: repo=https://github.com/vivaserver/MoonLion dest=~/.themes/MoonLion
  when: ansible_distribution_release == 'luna'
  tags:
    - eos

- name: ensure cruft removed
  apt: pkg={{ item }} state=absent purge=yes
  with_items:
    - empathy
    - empathy-common
  when: ansible_distribution_release == 'luna'
  sudo: yes
  tags:
    - eos
