---
- name: ensure i3 repo available
  apt_repository: repo='deb http://debian.sur5r.net/i3/ bionic universe'
  become: yes
  tags:
    - i3

- name: ensure i3 repo installable from
  command: apt-get --allow-unauthenticated install sur5r-keyring
  become: yes
  tags:
    - i3

- name: ensure i3 packages available
  apt:
    name: "{{ items }}"
    update_cache: yes
    state: latest
  vars:
    items:
      - i3
      - i3blocks
      - feh
      - fonts-font-awesome
      - lxappearance
      - lxterminal
      - rxvt-unicode-256color
      - xfonts-terminus
      - xsel
  become: yes
  tags:
    - i3
