---
- name: ensure i3-gaps repo available
  apt_repository: repo='ppa:kgilmer/regolith-stable'
  when: ansible_distribution_release == "bionic"
  become: yes
  tags:
    - i3

- name: ensure i3-gaps packages
  apt:
    name: "{{ items }}"
    update_cache: yes
    state: latest
  when: ansible_distribution_release == "bionic"
  vars:
    items:
      - i3-gaps

- name: ensure i3 packages
  apt:
    name: "{{ items }}"
    update_cache: yes
    state: latest
  vars:
    items:
      - i3blocks
      - feh
      - fonts-font-awesome
      - lxappearance
      - lxterminal
      - rxvt-unicode-256color
      - xfonts-terminus
      - xsel
  become: yes
  tags:
    - i3
