- name: ensure repo available
  apt_repository: repo='ppa:linrunner/tlp'
  become: yes
  tags: 
    - tlp
- name: ensure package available
  apt: pkg=tlp state=latest install_recommends=yes
  become: yes
  tags: 
    - tlp
