---
- include: ../../../tasks/build.yml
- import_tasks: console.yml
- include: desktop.yml
- include: ../../../tasks/dotfiles.yml
- include: elementaryos.yml
- import_tasks: laptop.yml
- include: i3wm.yml
- include: vim.yml
