---
- name: ensure Vim package
  apt: pkg=vim state=latest install_recommends=no
  when: ansible_distribution == 'Ubuntu'
  become: yes
  tags:
    - vim

- import_tasks: vim_vundle.yml
  when: ansible_distribution_release != "bionic"
  tags:
    - vim

- name: ensure vim-plug
  command: curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  when: ansible_distribution_release == "bionic"
  # :PlugInstall
  tags:
    - vim

- name: ensure essential Vim addons
  apt: pkg={{ item }} state=latest install_recommends=no
  with_items:
    - vim-airline
    - vim-airline-themes
    - vim-command-t
  when: ansible_distribution_release == "bionic"
  become: yes
  tags:
    - vim
