---
- name: Install Vim vundle plugin
  git: repo=https://github.com/gmarik/vundle.git dest=~/.vim/bundle/vundle
  tags: 
    - vundle

- name: ensure .vimrc_vundle included in config
  lineinfile: dest=~/.vimrc regexp='" source ~/.vimrc_vundle' line='source ~/.vimrc_vundle'
  tags: 
    - vundle

- name: Install Vim vundle plugins
  command: vim +BundleInstall +qall creates=.vim/bundle/ctrlp.vim
  tags: 
    - vundle
