---
- name: Install Vim vundle plugin
  git: repo=https://github.com/gmarik/vundle.git dest=~/.vim/bundle/vundle

- name: Install Vim vundle plugins
  command: vim +BundleInstall +qall creates=.vim/bundle/ctrlp.vim
