# Provision a development laptop
#
# 1. add "localhost" to /etc/ansible/hosts
# 2. install "ssh" package...
# 3. test host
#      $ ansible localhost -m setup
#      ....
#      $ ssh localhost
#      ....
# 4. $ ansible-playbook -vv --ask-sudo-pass --tags=tlp developer.yml
---
- hosts: localhost
  tasks:
    - name: ensure PPA repos addition supported
      apt: pkg=python-pycurl state=present
      become: yes

    # - import_tasks: tasks/docker_user.yml
    # - import_tasks: tasks/dropbox.yml
    # - import_tasks: tasks/google.yml
  roles:
    - developer
    # - rubyist
    # - phper
