# Provision an ElementaryOS development laptop
#
# 1. add "localhost" to /etc/ansible/hosts
# 2. install "ssh" package
# 3. $ ansible-playbook -vv --ask-sudo-pass --tags=tlp developer.yml
---
- hosts: localhost
  tasks:
    - name: ensure PPA repos addition supported
      apt: pkg=python-pycurl state=present

    # - import_tasks: tasks/dropbox.yml
    # - import_tasks: tasks/google.yml
  roles:
    - developer
    # - rubyist
    # - phper
