---
- name: ensure BitTorrent Sync repo.
  apt_repository: repo='ppa:tuxpoldo/btsync'
  sudo: yes

- name: ensure BitTorrent Sync package
  apt: pkg={{ item }} state=latest
  with_items:
    - btsync
    # - btsync-gui
  sudo: yes
