- name: ensure build packages installed
  apt: pkg={{ item }} state=latest
  with_items:
    - build-essential
    - libcurl4-openssl-dev
    - libncursesw5-dev
    - libpq-dev
    - libreadline6-dev 
    - libxml2 
    - libxml2-dev 
    - libxslt1-dev
    - libssl-dev
    - lxc
    - redir
  sudo: yes
