# ensure remote Docker support for Ansible Docker module
- name: ensure packages
  apt: pkg=python-setuptools state=latest
  when: ansible_distribution == "Ubuntu"

- name: ensure python support
  apt: pkg=python-pip
  when: ansible_distribution == "Ubuntu"

# ref. https://github.com/anarcher/ansible-docker-registry/issues/1
- name: ensure python support upgraded
  command: easy_install -U pip
  when: ansible_distribution_release == "trusty"

# ref. https://github.com/ansible/ansible/issues/10879#issuecomment-97738264
- name: ensure python support
  pip: name=docker-py version=1.1.0
  when: ansible_distribution_release == "trusty"

- name: ensure updated pip
  command: pip install --upgrade pip
  when: ansible_distribution_release == "xenial"

- name: ensure compose support
  pip: name=docker-compose
  when: ansible_distribution == "Ubuntu"
