# ref. https://stackoverflow.com/a/26399105
- name: get the username running the deploy
  local_action: command whoami
  register: remote_user
# - debug: var=remote_user

- name: add {{ remote_user.stdout }} to docker user
  user: name={{ remote_user.stdout }} groups=docker append=yes

# ref. http://stackoverflow.com/a/37334415
- name: add docker group to passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%docker'
    line: '%docker ALL=(ALL) NOPASSWD: ALL'

#- vim: foldlevel=3
