# ensure remote Docker support for Ansible Docker module
- name: ensure python support
  apt: pkg=python-pip
  when: ansible_distribution == "Ubuntu"
  sudo: yes

# ref. https://github.com/anarcher/ansible-docker-registry/issues/1
- name: ensure python support upgraded
  command: easy_install -U pip
  when: ansible_distribution == "Ubuntu"
  sudo: yes

# ref. https://github.com/ansible/ansible/issues/10879#issuecomment-97738264
- name: ensure python support
  pip: name=docker-py version=1.1.0
  when: ansible_distribution == "Ubuntu"
  sudo: yes
