- name: ensure repo key available
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present
  when: ansible_distribution == "Ubuntu" and ansible_distribution_release != "bionic"
  become: yes
  tags:
    - docker

- name: ensure official repo. for legacy Ubuntu
  apt_repository: repo="deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable" state=present
  when: ansible_distribution == "Ubuntu" and ansible_distribution_release != "bionic"
  become: yes
  tags:
    - docker

- name: ensure packages
  apt: name={{ packages }} update_cache=yes state=latest
  when: ansible_distribution == "Ubuntu" and ansible_distribution_release != "bionic"
  vars:
    packages:
      - docker-ce
  become: yes
  tags:
    - docker

- name: ensure packages
  apt: name={{ packages }} update_cache=yes state=latest
  when: ansible_distribution_release == "bionic"
  vars:
    packages:
      - docker.io
      - docker-compose
  become: yes
  tags:
    - docker
