- name: ensure repo key available
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present
  when: ansible_distribution == "Ubuntu"
  become: yes
  tags: 
    - docker

- name: ensure repo available
  apt_repository: repo='deb [arch=amd64] https://download.docker.com/linux/ubuntu trusty stable' state=present
  when: ansible_distribution_release == "trusty"
  become: yes
  tags: 
    - docker

- name: ensure repo available
  apt_repository: repo='deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable' state=present
  when: ansible_distribution_release == "xenial"
  become: yes
  tags: 
    - docker

- name: ensure packages
  apt: pkg={{ item }} update_cache=yes state=latest
  when: ansible_distribution == "Ubuntu"
  with_items:
    - docker-ce
  become: yes
  tags: 
    - docker
