# v20.04 LTS (focal)
# v18.04 LTS (bionic)
# v16.04 LTS (xenial)
# v14.04 LTS (trusty)

# ensure remote Docker support for Ansible Docker module
- name: ensure packages
  apt: pkg=python-setuptools state=latest
  when: ansible_distribution == "Ubuntu" and ansible_distribution_release != "bionic"

- name: ensure python support
  apt: pkg=python-pip
  become: yes
  when: ansible_distribution == "Ubuntu" and ansible_distribution_release == "bionic"

- name: ensure python support
  apt: pkg=python3-pip
  become: yes
  when: ansible_distribution == "Ubuntu" and ansible_distribution_release == "focal"

# ref. https://github.com/anarcher/ansible-docker-registry/issues/1
- name: ensure python support upgraded
  command: easy_install -U pip
  when: ansible_distribution_release == "trusty"
# ref. https://github.com/ansible/ansible/issues/10879#issuecomment-97738264
- name: ensure Ansible python support
  pip: name=docker-py version=1.1.0
  when: ansible_distribution_release == "trusty"

- name: ensure updated pip
  command: pip install --upgrade pip
  when: ansible_distribution_release == "xenial"

- name: ensure compose support
  pip: name=docker-compose
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version < "18.04"

- name: ensure compose support
  command: pip3 install docker-compose
  become: yes
  when: ansible_distribution_release == "focal"
  tags:
    - focal

- name: ensure Ansible python support
  when: ansible_distribution_release == "bionic"
  pip: name=docker
  become: yes

# vim: nofoldenable
