---
- name: Ensure packages available
  apt: pkg={{ item }} state=latest
  with_items:
    - curl
    - git
    - rsync
    - vim
    - wget
  sudo: yes

- name: Clone dot files
  git: repo=https://github.com/vivaserver/dotfiles dest=~/dotfiles
- name: Install dot files
  command: ~/dotfiles/install.sh --force creates=.gitconfig

# same as in /etc/environment?
- name: fix locale
  lineinfile: dest=/etc/default/locale line='LANGUAGE="en_US:en"'
  sudo: yes
  tags:
    - locale
- name: fix locale
  lineinfile: dest=/etc/default/locale line='LC_ALL="en_US.UTF-8"'
  sudo: yes
  tags:
    - locale
- name: fix locale
  lineinfile: dest=/etc/default/locale line='LANG="en_US.UTF-8"'
  sudo: yes
  tags:
    - locale
- name: fix locale
  command: sudo locale-gen en_US.UTF-8
  sudo: yes
  tags:
    - locale
