---
- name: Ensure packages available
  apt: pkg={{ item }} state=latest
  with_items:
    - curl
    - git
    - rsync
    - vim
    - wget
  sudo: yes

- name: Clone dot files
  git: repo=https://github.com/vivaserver/dotfiles dest=~/dotfiles
- name: Install dot files
  command: ~/dotfiles/install.sh --force creates=.gitconfig
