---
- name: ensure Dropbox repo available
  apt_repository: repo='deb http://linux.dropbox.com/ubuntu precise main'
  sudo: yes

- name: ensure Dropbox package available
  apt: pkg=dropbox state=latest
  sudo: yes
