- name: ensure Google repo key available
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present
  become: yes
  tags: 
    - google

- name: ensure Google Chrome repo available
  apt_repository: repo='deb http://dl.google.com/linux/chrome/deb/ stable main' state=present
  become: yes
  tags: 
    - google

# - name: ensure Google Talk repo available
#   apt_repository: repo='deb http://dl.google.com/linux/talkplugin/deb/ stable main' state=present
#   sudo: yes

- name: ensure Google packages
  apt: pkg={{ item }} update_cache=yes state=latest
  with_items:
    - google-chrome-stable
  # - google-talkplugin
  become: yes
  tags: 
    - google
