---
- name: Ensure packages available
  apt: pkg={{ item }} state=present install_recommends=no
  with_items:
    - libapache2-mod-php5
    - mysql-server
    - php5-cli
    - php5-curl
    - php5-gd
    - php5-mysql
  sudo: yes

- name: Ensure LA(M)P is running
  service: name=mysql state=started
  sudo: yes

- name: Ensure nice default HTTP index
  copy: src=www.html dest=/var/www/index.html
  sudo: yes

- name: Ensure nice default favicon
  copy: src=favicon.ico dest=/var/www
  sudo: yes

- name: ensure inclusion of virtual host configurations
  lineinfile: dest=/etc/apache2/apache2.conf regexp='' insertafter=EOF line="Include sites-enabled/" state=present
  notify: restart apache2
  sudo: yes

- name: ensure no fully qualified domain name error
  lineinfile: dest=/etc/apache2/httpd.conf regexp='' insertafter=EOF line='ServerName localhost' state=present
  notify: restart apache2
  sudo: yes

- name: Ensure Apache2 modules
  command: a2enmod rewrite creates=/etc/apache2/mods-enabled/rewrite.load
  notify: restart apache2
  sudo: yes
