- name: ensure Node build repos
  apt_repository: repo='ppa:chris-lea/node.js'
  when: ansible_distribution == "Ubuntu"
  sudo: yes

- name: ensure Node packages installed
  apt: pkg={{ item }} state=latest
  when: ansible_distribution == "Ubuntu"
  with_items:
    - nodejs
  sudo: yes
