# default MySQL user=root, password=''
---
- name: Ensure phpmyadmin available
  apt: pkg=phpmyadmin state=present install_recommends=no
  sudo: yes

- name: Ensure phpmyadmin setup
  copy: src=phpmyadmin.conf dest=/etc/dbconfig-common/
  sudo: yes

- name: Ensure phpmyadmin configured
  copy: src=phpmyadmin.php dest=/etc/phpmyadmin/config.inc.php
  sudo: yes

- name: ensure phpmyadmin installed
  command: ln -s /etc/phpmyadmin/apache.conf /etc/apache2/conf.d/phpmyadmin.conf creates=/etc/apache2/conf.d/phpmyadmin.conf
  sudo: yes

- name: ensure phpmyadmin site reloaded
  service: name=apache2 state=restarted
  sudo: yes
