---
# ref. http://www.ubuntuupdates.org/ppa/brightbox_ruby_ng_experimental?dist=precise
- name: ensure old Ruby 1.9.3 package removed
  apt: pkg=ruby1.9.1 state=absent
  sudo: yes

- name: ensure Ruby NG repo available
  apt_repository: repo='ppa:brightbox/ruby-ng-experimental'
  sudo: yes

- name: ensure Ruby 1.9.3 package available
  apt: pkg={{ item }} update_cache=yes
  with_items:
    - ruby1.9.3
    - ruby-switch
    - rubygems
  sudo: yes
