---
- name: ensure site VirtualHost available
  template: src=vhost.j2 dest=/etc/apache2/sites-available/{{ vhost_name }} mode=0644
  sudo: yes

- name: ensure site VirtualHost setup
  command: a2ensite {{ vhost_name }} creates=/etc/apache2/sites-enabled/{{ vhost_name }}
  notify: restart apache2
  sudo: yes
